train:
  batch_size: &BATCH_SIZE 512
  device: &DEVICE 'cuda'
  max_epochs: 100

# There is some overlap between Dataset and DataLoader parameters
# they are all grouped here with explanations.
data:
  # Spectrogram parameters.
  mfcc:
    n_mfcc: 13
  img_size: &IMG_SIZE 64
  mean: 0.5 # This is better than no normalisation.
  std: 0.5

  # DataLoader parameters
  device: *DEVICE
  batch_size: *BATCH_SIZE
  num_workers: 4
  pin_memory: True
  prefetch_factor: 8
  # Stats for the training dataset, used to scale 0 - 1.
  global_min: -1818
  global_max: 618

model:
  resnet_variant: 'resnext50'
  dropout: 0.4
  unfreeze_layers: -1
  img_size: *IMG_SIZE
  optimiser:
    sgd:
      momentum: 0.9
      weight_decay: 0.0001
      lr: 0.1 # Usually have lower LR, but here 0.1 works well for this problem.
